// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:workout_app/models/api_meta.dart';
import 'package:workout_app/models/diet_nutrition_goals.dart';
import 'package:workout_app/models/meal.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ApiMetaAdapter());
    registerAdapter(DailyNutritionGoalsAdapter());
    registerAdapter(MealAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ApiMetaAdapter());
    registerAdapter(DailyNutritionGoalsAdapter());
    registerAdapter(MealAdapter());
  }
}
