// lib/main.dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_ce_flutter/hive_flutter.dart';
// New initialization flow pieces
import 'package:workout_app/Api/exercise_api_service.dart';
import 'package:workout_app/cache/exercise_image_cache.dart';
// Import Firebase options (you'll need to generate this with FlutterFire CLI)
import 'package:workout_app/firebase_options.dart';
// Keep your generated Hive registrar
import 'package:workout_app/hive_registrar.g.dart';
import 'package:workout_app/presentation/screens/diet_screen.dart';
import 'package:workout_app/presentation/screens/home_screen.dart';
import 'package:workout_app/presentation/screens/initialize/app_initializer.dart';
import 'package:workout_app/presentation/screens/initialize/initialization_screen.dart';
import 'package:workout_app/presentation/screens/initialize/welcome_screen.dart';
import 'package:workout_app/presentation/screens/profile_screen.dart';
import 'package:workout_app/presentation/screens/progress_screen.dart';
// App screens and theme from your old structure
import 'package:workout_app/presentation/screens/workouts_screen.dart';
// Repositories
import 'package:workout_app/repository/exercise_cache_repository.dart';
import 'package:workout_app/theme/theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize Hive
  await Hive.initFlutter();

  // Register adapters generated by your build step
  Hive.registerAdapters();

  // Run app inside ProviderScope so Riverpod remains available
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Workout App',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      home: const AuthenticationWrapper(),
    );
  }
}

/// Wrapper that checks authentication status
class AuthenticationWrapper extends StatelessWidget {
  const AuthenticationWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // Show loading while checking auth state
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // User is signed in
        if (snapshot.hasData && snapshot.data != null) {
          return const AppInitializationWrapper();
        }

        // User is not signed in
        return const WelcomeScreen();
      },
    );
  }
}

/// Wrapper that checks if app is initialized and shows appropriate screen
class AppInitializationWrapper extends StatefulWidget {
  const AppInitializationWrapper({super.key});

  @override
  State<AppInitializationWrapper> createState() =>
      _AppInitializationWrapperState();
}

class _AppInitializationWrapperState extends State<AppInitializationWrapper> {
  bool _isLoading = true;
  bool _isInitialized = false;
  late AppInitializer _initializer;

  // Keep references so we don't re-open boxes repeatedly
  static const String exerciseCacheBoxName = 'exercise_cache_box';
  static const String initBoxName = 'app_init_box';

  @override
  void initState() {
    super.initState();
    _checkInitialization();
  }

  Future<void> _checkInitialization() async {
    try {
      // Open required boxes (safe to open here)
      final exerciseCacheBox = await Hive.openBox(exerciseCacheBoxName);
      final initBox = await Hive.openBox(initBoxName);

      // Create services
      final apiService = ExerciseApiService();
      final cacheRepo = ExerciseCacheRepository(apiService, exerciseCacheBox);
      final imageCache = ExerciseImageCache();

      // Create initializer
      _initializer = AppInitializer(cacheRepo, imageCache, initBox);

      // Check if already initialized (synchronous helper)
      final isInit = _initializer.isInitialized();

      setState(() {
        _isInitialized = isInit;
        _isLoading = false;
      });
    } catch (e, st) {
      // If initialization check fails, surface a fatal error UI rather than silently crashing.
      setState(() {
        _isLoading = false;
        _isInitialized = false;
      });
      // ignore: avoid_print
      print('Initialization check failed: $e\n$st');
    }
  }

  void _onInitializationComplete() {
    setState(() {
      _isInitialized = true;
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const Scaffold(body: Center(child: CircularProgressIndicator()));
    }

    if (!_isInitialized) {
      return InitializationScreen(
        initializer: _initializer,
        onComplete: _onInitializationComplete,
      );
    }

    return const MainNavigationScreen();
  }
}

class MainNavigationScreen extends StatefulWidget {
  const MainNavigationScreen({super.key});

  @override
  State<MainNavigationScreen> createState() => _MainNavigationScreenState();
}

class _MainNavigationScreenState extends State<MainNavigationScreen> {
  int _currentIndex = 0;

  final List<Widget> _screens = [
    const HomeScreen(),
    const WorkoutsScreen(),
    const DietScreen(),
    const ProgressScreen(),
    const ProfileScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _screens[_currentIndex],
      bottomNavigationBar: NavigationBar(
        animationDuration: const Duration(milliseconds: 500),
        selectedIndex: _currentIndex,
        onDestinationSelected: (index) {
          setState(() {
            _currentIndex = index;
          });
        },
        destinations: const [
          NavigationDestination(
            icon: Icon(Icons.home_outlined),
            selectedIcon: Icon(Icons.home),
            label: 'Home',
          ),
          NavigationDestination(
            icon: Icon(Icons.fitness_center_outlined),
            selectedIcon: Icon(Icons.fitness_center),
            label: 'Workouts',
          ),
          NavigationDestination(
            icon: Icon(Icons.restaurant_outlined),
            selectedIcon: Icon(Icons.restaurant),
            label: 'Diet',
          ),
          NavigationDestination(
            icon: Icon(Icons.trending_up_outlined),
            selectedIcon: Icon(Icons.trending_up),
            label: 'Progress',
          ),
          NavigationDestination(
            icon: Icon(Icons.person_outline),
            selectedIcon: Icon(Icons.person),
            label: 'Profile',
          ),
        ],
      ),
    );
  }
}
